version: 2.1
orbs:
  snyk: snyk/snyk@2.2.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - snyk/scan
        monitor-on-build: true

workflows: null
