version: '2.1'
orbs:
  snyk: snyk/snyk@2.2.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: nvm install
      - snyk/scan
        fail-on-issues: false
        monitor-on-build: true

workflows: 
  build-test-snyk:
    jobs:
      - snyk-scan
